### ISSUE TITLE
What is the current state and planned future of WebForms?

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/Fritz.LiveStream#10]
Asked by electricessense on Twitter:
https://twitter.com/electricessence/status/941900690116378624

**Comment by csharpfritz** [comment]
Answered in Dec. 16th stream.

**Comment by jdalley** [comment]
Link to the docker blog speaking to Windows licensing; doesn't seem _too_ out of date: https://blog.docker.com/2017/01/docker-windows-server-image2docker/

Short version: You can have any number of docker containers on a licensed Windows host.

**Comment by csharpfritz** [comment]
Answered on the live stream and blogged at: http://jeffreyfritz.com/2017/12/whats-new-in-web-forms-work-on-our-asp-net-core-project-with-the-mixer-and-twitch-apis/
