### ISSUE TITLE
Custom colors for follower bar progress

### ISSUE THREAD

**Issue by kirkdmo** [csharpfritz/Fritz.LiveStream#22]
Would be nice to have the follower goal progress bar change colors (or have an option to do this) as it gets closer to the goal number.

For example

Follower Goal of 500
1 to 100 be red
100 to 200 orange
200 to 300 yellow
400 to 500 green

**Comment by csharpfritz** [comment]
Migrated to csharpfritz/Fritz.StreamTools#14
