### ISSUE TITLE
ASP.NET Core - How do you add Bootstrap Components?

### ISSUE THREAD

**Issue by VorTechS** [csharpfritz/Fritz.LiveStream#30]
I've started my first ASP.NET Core project, and am on a vertical learning curve learning MVC and Razor at the same time.

In the old ASPX days, adding JS scripts was pretty simple using the <script> tag and nowadays of course many things are achievable through NuGet.

ASP.NET Core bundles bootstrap, but it doesn't contain a decent DatePicker which I need.  I tried adding the NuGet package Bootstrap.v3.DatePicker to my project, but the jQuery function '.datepicker()' is not defined, because the JS isn't being loaded.

From a brief look around, it looks like I need to manage my bundle configuration, but the instructions I can see floating around are related to BundleConfig.cs in _AppData which doesn't exist in ASP.NET Core.

There is a BundleConfig.js however, and I can see some input files and output files relating to the wwroot directory.  But I have no idea how to reference the downloaded NuGet package which doesn't appear to have put anything in my packages folder.

Please help!

**Comment by Eonasdan** [comment]
@VorTechS I created a tag helper for my datepicker turned it into [a gist](https://gist.github.com/Eonasdan/afe99a3c349ba37e1462fe20ccd75fee), just for you.

**Comment by VorTechS** [comment]
Thanks Eonasdan, a tag helper would certainly be useful!  the issue isn't so much about how to interact with the component.  What I'm talking about here, is that when added via NuGet the component doesn't appear to be 'referenced' (hence any calls to .datepicker() are not valid).  

If I manually download the js source, and reference it in the relevant cshtml file (or layout file) then everything works as you'd expect.  But if I try using NuGet to do this, there's no sign of the downloaded source and it's not referenced anywhere meaning it can't be used 'out of the box with no other interaction'.  Or, if it is downloaded, I couldn't find where it was hiding.

**Comment by Eonasdan** [comment]
sorry @csharpfritz didn't mean to make this a rabbit trail. @VorTechS you should still be able to base your needs for the old picker to the tag helper included, but you'll have to modify it to work for the syntax of the old picker.

**Comment by VorTechS** [comment]
It's okay, as I was saying - I was hoping things would just be a case of just being able to 'NuGet' the package and Visual Studio would put all the relevant JS files in the right place in the project.

**Comment by csharpfritz** [comment]
I LOVE the idea of being able to just NuGet install a package of TagHelpers and the UI just works. 

I think we, as an AspNet Community need to have some good design guidelines to make it easier for folks to build user interface components that help minimize the back and forth across various package managers and components. If we had some better guidelines, or perhaps a way to drive automation of some of these things, we would all get an amazing experience. 

I think that automation or guideline is something we could assemble without much work. 



Jeff

**Comment by VorTechS** [comment]
Let's do it!  What do we have to do to get this moving forward?
