### ISSUE TITLE
Discuss targeting a .NET 2.0 Standard library on older .NET Framework even if API is in that framework

### ISSUE THREAD

**Issue by SpaceShot** [csharpfritz/Fritz.LiveStream#4]
What I am looking for is how does it work if an API is supported in something like .NET Framework but that particular framework DOES NOT support the standard that contains the API.

The specific API I ran into this with is System.Net.WebSockets.WebSocket.  It is in .NET Standard 2.0 but it's supported as far back as .NET Framework 4.5.

https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.websocket

How would you go about using a .NET Standard 2.0 library that used Websocket but wanted to CONSUME that from a .NET Framework that has the API, but yet doesn't implement all of .NET Standard 2.0.

Does it "just work"?  Maybe it's not really a big deal as these .NET Frameworks end support.  But some .NET Frameworks shipped with  Windows and have a long "lifespan"

**Comment by csharpfritz** [comment]
I need some idea of which API you would like help with...

**Comment by SpaceShot** [comment]
Specifically, I came across this with the WebSockets API.  
For example: System.Net.WebSockets.ClientWebSocket class.

It's part of .NET Framework as early as .NET Framework 4.5.1.  But 4.5.1 only implements .NET Standard 1.2.  It's  not implemented in .NET Standard until 2.0.  If I used a library (like maybe... a Mixer library perhaps) that targeted .NET Standard 2.0, could it be consumed in a .NET Framework 4.5.1 app?  

Does the tooling get in your way?
Do you have to ignore/suppress warnings?
Anything I am missing?  Does it "just work"?

**Comment by csharpfritz** [comment]
Started talking about using PCL and .NET Standard.  Add them to the same NuGet package, pivot for each framework.
