### ISSUE TITLE
Revisiting Docker with Databases

### ISSUE THREAD

**Issue by Eldorian** [csharpfritz/Fritz.LiveStream#43]
In the ASP.NET workshop, you and Julie started using SQLLite to build the database and then seed it with a method.

Later on, you and Shane implemented using MSSQL server for Linux, however, the only thing that was changed with that is your authorization entities got moved over to that, but your trips database is still being built with SQLLite in your startup on your backservice.

Would you be able to show us how to move that SQLLite database over to the one on the docker container and have it still seed the data on the MSSQL Linux server?

**Comment by csharpfritz** [comment]
Answered on Jan 4, 2019
