### ISSUE TITLE
What is the best way to display version numbers in a web site with CI/CD?

### ISSUE THREAD

**Issue by OpenWindow** [csharpfritz/Fritz.LiveStream#45]
@csharpfritz, Saw few web sites displaying version numbers of their product in the footer. If I want to update version numbers with each build/deployment from CI/CD build server, what is the best way/place to store the build numbers and display it on the web site?

**Comment by csharpfritz** [comment]
Answered in March 17, 2018 stream.  Thanks for your question!

**Comment by smabuk** [comment]
Watching this in the stream live last week I didn't have access to the chat (bandwidth issues) and there are some things that don't work with the approach you suggested.

It inspired me to create a site comparing different ways of setting up your version information and how to consistently and correctly get access to the version that you require.

The project on github is at https://github.com/smabuk/versioningdemos and you can see the differences between running locally or running it live in production at https://versioningdemos.azurewebsites.net/

Is it worth me creating a Pull request on the Version TagHelper given you are about to move onto other things? My TagHelper code is at: [versionTagHelper.cs](https://github.com/smabuk/VersioningDemos/blob/master/TagHelperLibrary/VersionTagHelper.cs)

It might be worth a mention as it does explain how assemblies aren't always what you'd expect in ASP.NET Core 2.x, especially when working as a developer. The "it worked on my machine", definitely in evidence here.

**Comment by csharpfritz** [comment]
This is a great idea and thank you for your comments. I’ll re-open this issue and integrate your suggestion on Thursday’s stream. 

Big thanks for the feedback!
