### ISSUE TITLE
Consume Web API using ASP.Net Core Web Application

### ISSUE THREAD

**Issue by Bobbybong** [csharpfritz/Fritz.LiveStream#47]
Do you have a working code on how to consume ASP.Net Web API using ASP.Net Core Web Application?

**Comment by csharpfritz** [comment]
We reviewed a sample on the May 15th show and you can find more in the Microsoft docs at:  https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/calling-a-web-api-from-a-net-client
