### ISSUE TITLE
Planning for Architecture Workshop in July

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/Fritz.LiveStream#58]
We've hit 2000 followers and we've promised an architecture workshop for hitting that goal.

Let's recruit some speakers and plan the content.

Jimmy Bogard to talk about mediatr? [interested]
Steve Smith?

Who else and what topics would you like to hear about?  

CQRS?

**Comment by asyncawake** [comment]
Architecture workshop refers to application architecture, not .NET Framework architecture, correct?
Would SOLID be to basic of a topic? I think inviting Tim Corey who did a great series on SOLID on youtube would be awesome for a beginner friendly segment of that workshop...

**Comment by benrick** [comment]
That's correct, @asyncawake .

**Comment by csharpfritz** [comment]
Application or Systems architecture are within scope for this event.

I did an hour with Phil Japikse on SOLID concepts during the C# workshop at:  https://www.youtube.com/watch?v=PH8GugzXmMo&t=4s 


Jeff

**Comment by csharpfritz** [comment]
We're ON!  Tomorrow, July 20th -- https://www.twitch.tv/events/RiYlEN-dTJiCt9Xz0nx4_w
