### ISSUE TITLE
.net core 2.1 issue

### ISSUE THREAD

**Issue by nmalocic** [csharpfritz/Fritz.LiveStream#61]
Hi everyone,

I wanted to ask question about .net 2.1 and why i was getting error saying that 2.1.0 version can't be found.
I resolved issue by manually renaming C:\program files\dotnet\shared\...\2.1.0-rc1-review to ...\2.1.0 and then CoreWiki project started working?

Is this because 2.1.0 is not released yet?

**Comment by csharpfritz** [comment]
2.1 is now arriving on NuGet.org -- you should be able to start using the RTM version (2.1.0 and netcoreapp2.1) today with no additional repositories configured in your application.  There are a blog posts from the ASP.NET team and .NET teams coming when everything is deployed

**Comment by nmalocic** [comment]
@csharpfritz  thank you for fast answer, will you move CoreWiki/StreamTools to 2.1 version?
I think i had issue that StreamTools is using 2.1.0-rc1-final that i also didn't have installed so i had to pull and install. I guess both projects should be 2.1 RTM after release?

**Comment by csharpfritz** [comment]
Yes.. I'll be updating both projects to 2.1

**Comment by nmalocic** [comment]
I think we can close this one, i think projects are updated to 2.1?

**Comment by csharpfritz** [comment]
I think they are...  lets close it
