### ISSUE TITLE
Architecture  / class diagrams?

### ISSUE THREAD

**Issue by nmalocic** [csharpfritz/Fritz.LiveStream#64]
It is possible it's only me, but i noticed that Wiki/StreamTools are getting bigger and more complex.

Does it make sense to create at least architecture diagrams for this projects so that new people could get up to speed easier? 
This will add additional overhead because we will need to maintain this diagrams also.

**Comment by csharpfritz** [comment]
Sure... we can create some diagrams to make it clear how the application is structured

**Comment by csharpfritz** [comment]
Completed...
