### ISSUE TITLE
Update README.md to correct section "Watch LIVE"

### ISSUE THREAD

**Issue by swixfort** [csharpfritz/Fritz.LiveStream#69]
This section still talks about "Mixer" while the Mixer channel claims that you seized using it due to the lack of ability to provide high quality interaction with Mixer.

Why, by the way? What's the issue?

**Comment by csharpfritz** [comment]
I'll yank the Mixer element on the README.

Mixer does not support the Edge browser properly, does not support closed captioning, and has a number of other shortcomings for broadcasters that I have shared directly with the Mixer team.  Once Mixer is in a better position with respect to these features, I'm happy to reconsider using the service

**Comment by csharpfritz** [comment]
Updated README
