### ISSUE TITLE
What VSCode extensions have you installed?

### ISSUE THREAD

**Issue by msschl** [csharpfritz/Fritz.LiveStream#71]
Hi Jeffrey,

i know that you had one stream in the past where you showed all your current installed visual studio code extensions. But unfortunately i can't remember which stream it was.

It would be realy nice to add this question into your [FAQ](https://github.com/csharpfritz/Fritz.LiveStream/wiki/Frequently-Asked-Questions).

Greetings form Germany, Düsseldorf
Markus

**Comment by csharpfritz** [comment]
Added to the FAQ and answered on January 3, 2019 stream
