### ISSUE TITLE
Christmas Stories with Fritz

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/Fritz.LiveStream#78]
What stories would you like me to read?  

Scheduled for Sunday December 23.  Turn the green screen into a fireplace, make it look all cozy and full of holiday cheer

Charity stream -- all cheers / donations to?

**Comment by chekm8** [comment]
Polar Express.

What about something local like for kids stuck in CHOP over the holidays?

**Comment by lqdev** [comment]
__The Legend of Belsnickel__

![](https://media.tenor.com/images/aae14dc84b7890489d4ff021fc77f656/tenor.gif)

**Comment by AdmiralSnyder** [comment]
Maybe you can get Jon Skeet to read another part of the C# spec for a couple of minutes :-)
