### ISSUE TITLE
Day of Service - Virtual Hackathon

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/Fritz.LiveStream#79]
For the Martin Luther King Jr. Day of Service (January 21, 2019), lets take on a virtual hackathon across live streams and locations TOGETHER.  We will together build an open-source application for a non-profit organization.

The idea started with a request from [Sebastian Riding Associates](http://sebastianriding.org/) a non-profit therapeutic riding center, to help construct an internet application to help with scheduling and resource management.  There are many potential facets to this application, and a tremendous learning opportunity for anyone who wishes to participate.

The resultant application will be open source (MIT License) and available for customization by any organization that wishes to customize, enhance, or deploy it in the future.

We will recruit streamers, programmers, artists, and anyone who wishes to contribute.

The code and requirements will be built out at:  https://github.com/FritzAndFriends/ResourceManagement

**Comment by csharpfritz** [comment]
From the [initial Twitter discussion](https://twitter.com/csharpfritz/status/1073693360525856768), these individuals have expressed interest in assisting:

@DigitalOxCanada
@nibro7778
@justinhhorner
@rich_ross
@jimbobbennett

**Comment by csharpfritz** [comment]
Ideas:

- Recruit sponsors to assist streamers with tools / resources / swag / giveaways to help promote the event
- Establish a Twitch Stream Team to cross-promote streamers

**Comment by WodeCraft** [comment]
Would love to be a part of this ... looking forward to more information :)

**Comment by hugodahl** [comment]
Sign me up to be part of this great effort!

**Comment by FBoucher** [comment]
Jeff, count me in!

**Comment by M-Zuber** [comment]
I would love to participate!

**Comment by vahurtad** [comment]
Also would like to participate!
Maybe a design is needed to promote the event and  commucation should go through a discord.

**Comment by csharpfritz** [comment]
A design / logo would be great!  Any ideas who can help with that?


Jeff

**Comment by FBoucher** [comment]
How about something like this?

![riding-logo](https://user-images.githubusercontent.com/2404846/50248126-f79a0a00-03a7-11e9-8cba-c03bdf5068df.png)

**Comment by vahurtad** [comment]
I unfortunately don't know anyone who can help with the logo. But I wouldn't mind doing a simple sketch like @FBoucher did or anybody else who wants to contribute.

**Comment by csharpfritz** [comment]
Did not complete and will not reschedule
