### ISSUE TITLE
Discussion on GraphQL

### ISSUE THREAD

**Issue by lannonbr** [csharpfritz/Fritz.LiveStream#81]
I remember some stream last month someone brought up GraphQL and @csharpfritz commented that he doesn't use it particularly and said that the things it solves were already made.

Would it be possible to further explain that in a future stream during the AMA section of the stream on what you meant by that?

**Comment by mtheoryx** [comment]
I would also like an opportunity to add thoughts from "the other side" but perhaps that's best left as an exercise in my own stream to not intrude on another streamer's social platform.
