### ISSUE TITLE
Create a list of regular viewers and community members who stream

### ISSUE THREAD

**Issue by hugodahl** [csharpfritz/Fritz.LiveStream#86]
As a viewer who is interested in watching other members of the community, I would like to have a list of people who also stream and have a link to find out more about them and their streams.

Source: [Discord chat](https://discordapp.com/channels/389226088607252490/534865628029255697/539910639779577913)

**Comment by leemw1977** [comment]
I like the idea, I wonder if @csharpfritz has a notion to setup a stream team when he hits partner, but being able to get this info outside of twitch seems more approachable, depends on what plan there is for major mischief :)

**Comment by csharpfritz** [comment]
Stream Team is set:

https://twitch.tv/team/livecoders

**Comment by mtheoryx** [comment]
I think the stream team, and using the team info box on your page sufficiently closes this issue.

**Comment by csharpfritz** [comment]
Agreed with @mtheoryx - closing
