### ISSUE TITLE
Asp.net deploy to synology NAS

### ISSUE THREAD

**Issue by DukaSoft** [csharpfritz/Fritz.LiveStream#95]
Hi @csharpfritz, we talked about deploying asp.net to a synology.
Hope this is the right place to remind you about that :)

Also, thanks soo much for all of your hard work!

**Comment by mjfreelancing** [comment]
This is of interest too me too, thanks

**Comment by csharpfritz** [comment]
Answered and demoed on July 16, 2020 stream

**Comment by mjfreelancing** [comment]
I missed the stream. Was the video recorded (may be it hasn't been uploaded yet)?

**Comment by DukaSoft** [comment]
> I missed the stream. Was the video recorded (may be it hasn't been uploaded yet)?

https://www.twitch.tv/videos/681326743
Its in there :)

Also, thanks Fritz!

**Comment by mjfreelancing** [comment]
> https://www.twitch.tv/videos/681326743
> Its in there :)

Thanks, I didn't see it earlier.
